server:
  port: 8091
  context-path: /fms

file:
  rootFolder: /Users/Ganesan/Work/Assay/FMS

info:
    app.name: File Management System Service
    build.version: 0.1.0-XXX

spring:
 jpa:
    database: POSTGRESQL
    show-sql: true
 datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-52-48-133-9.eu-west-1.compute.amazonaws.com:5432/test_db
    username: testdev
    password: testdev123
    driverClassName: org.postgresql.Driver

multipart:
  maxFileSize: -1