server:
  port: 8091
  context-path: /fms

file:
  rootFolder: /Users/Ganesan/Work/Assay/FMS

info:
    app.name: File Management System Service
    build.version: 0.1.0-XXX

spring:
 jpa:
    database: POSTGRESQL
    show-sql: true
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/FMS
    username: FMS
    password: changeme
    driverClassName: org.postgresql.Driver

multipart:
  maxFileSize: -1