server:
  port: 8090
  context-path: /fms

file:
  rootFolder: /Users/Ganesan/Work/Assay/FMS

info:
    app.name: File Management System Service
    build.version: 0.1.0-XXX

spring:
 jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
 datasource:
    data: classpath:/master.sql