INSERT INTO FMS_MA_UPLOAD_CATEGORY(UC_ID,UC_NAME,UC_DESC) VALUES (NULL,'STUDENT','STUDENT DETAILS');
INSERT INTO FMS_MA_CATEGORY_DOCTYPE(CD_ID,CD_TYPE,CD_UC_ID,CD_DESC,CD_MULTIPLE)
                              VALUES (NULL,'PAN CARD',1,'Pan Card Details',TRUE);
INSERT INTO FMS_MA_UPLOAD_CATEGORY(UC_ID,UC_NAME,UC_DESC) VALUES (NULL,'TEACHER','TEACHER DETAILS');
INSERT INTO FMS_MA_CATEGORY_DOCTYPE(CD_ID,CD_TYPE,CD_UC_ID,CD_DESC,CD_MULTIPLE)
                              VALUES (NULL,'PAN CARD',2,'Pan Card Details',TRUE);


